networks:
  default:
    name: evolve
    external: true
    driver: bridge

services:
  evolve:
    container_name: evolve
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Monta o arquivo de configuração do nginx
      # - /app/dist/evolve:/usr/share/nginx/html       # Monta os arquivos da aplicação
    ports:
      - "4200:80"