#Servidor http da aplicação angular
server {
    listen 80;
    server_name evolve;

    root /usr/share/nginx/html;
    index index.html;

    # Rota para o proxy para o collector
    location /collector/v1/traces {
        proxy_pass http://loadbalancer:4318/v1/traces;
    }

    # Rota para servir a aplicação Angular
    location / {
        try_files $uri $uri/ /index.html;
    }
    
}