export enum Permission{
    EDIT_TEAM_INFO,
    MANAGE_PARTICIPANTS,
    CREATE_PROJECT,
    TEAM_CREATOR,
    TEAM_VIEW,
    EDIT_PROJECT_INFO,
    MANAGE_MEMBERS,
    CREATE_TASK,
    PROJECT_CREATOR,
    PROJECT_VIEW,
}