export enum PropertyType{
    TEXT = "TEXT",
    DOUBLE = "DOUBLE",
    INTEGER = "INTEGER",
    DATE = "DATE",
    MULTISELECT = "MULTISELECT",
    UNISELECT = "UNISELECT",
    ASSOCIATES= "ASSOCIATES"
}